// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package acme_external_account_binding

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AcmeEndpointARN, b.ko.Spec.AcmeEndpointARN) {
		delta.Add("Spec.AcmeEndpointARN", a.ko.Spec.AcmeEndpointARN, b.ko.Spec.AcmeEndpointARN)
	} else if a.ko.Spec.AcmeEndpointARN != nil && b.ko.Spec.AcmeEndpointARN != nil {
		if *a.ko.Spec.AcmeEndpointARN != *b.ko.Spec.AcmeEndpointARN {
			delta.Add("Spec.AcmeEndpointARN", a.ko.Spec.AcmeEndpointARN, b.ko.Spec.AcmeEndpointARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.AcmeEndpointRef, b.ko.Spec.AcmeEndpointRef) {
		delta.Add("Spec.AcmeEndpointRef", a.ko.Spec.AcmeEndpointRef, b.ko.Spec.AcmeEndpointRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Expiration, b.ko.Spec.Expiration) {
		delta.Add("Spec.Expiration", a.ko.Spec.Expiration, b.ko.Spec.Expiration)
	} else if a.ko.Spec.Expiration != nil && b.ko.Spec.Expiration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Expiration.Type, b.ko.Spec.Expiration.Type) {
			delta.Add("Spec.Expiration.Type", a.ko.Spec.Expiration.Type, b.ko.Spec.Expiration.Type)
		} else if a.ko.Spec.Expiration.Type != nil && b.ko.Spec.Expiration.Type != nil {
			if *a.ko.Spec.Expiration.Type != *b.ko.Spec.Expiration.Type {
				delta.Add("Spec.Expiration.Type", a.ko.Spec.Expiration.Type, b.ko.Spec.Expiration.Type)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Expiration.Value, b.ko.Spec.Expiration.Value) {
			delta.Add("Spec.Expiration.Value", a.ko.Spec.Expiration.Value, b.ko.Spec.Expiration.Value)
		} else if a.ko.Spec.Expiration.Value != nil && b.ko.Spec.Expiration.Value != nil {
			if *a.ko.Spec.Expiration.Value != *b.ko.Spec.Expiration.Value {
				delta.Add("Spec.Expiration.Value", a.ko.Spec.Expiration.Value, b.ko.Spec.Expiration.Value)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RoleARN, b.ko.Spec.RoleARN) {
		delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
	} else if a.ko.Spec.RoleARN != nil && b.ko.Spec.RoleARN != nil {
		if *a.ko.Spec.RoleARN != *b.ko.Spec.RoleARN {
			delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.RoleRef, b.ko.Spec.RoleRef) {
		delta.Add("Spec.RoleRef", a.ko.Spec.RoleRef, b.ko.Spec.RoleRef)
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
