// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AcmeExternalAccountBindingSpec defines the desired state of AcmeExternalAccountBinding.
//
// Contains detailed information about an ACME external account binding.
type AcmeExternalAccountBindingSpec struct {

	// The ARN of the ACME endpoint to associate this external account binding with.
	//
	// The Amazon Resource Name (ARN) of the ACME endpoint.
	//
	// Regex Pattern: `^arn:aws[a-z-]*:acm:[a-z0-9-]+:[0-9]{12}:acme-endpoint/[a-zA-Z0-9-]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	AcmeEndpointARN *string                                  `json:"acmeEndpointARN,omitempty"`
	AcmeEndpointRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"acmeEndpointRef,omitempty"`
	// The Kubernetes Secret where EAB credentials are written. Specify the namespace,
	// name, and key. The sensitive macKey is written under the given key; the keyId is
	// written under a fixed keyId key, unless key is itself keyId, in which case the
	// macKey wins and the identifier is available in status.keyID. If namespace is
	// omitted, the resource's namespace is used. The Secret must already exist; the
	// controller populates it.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	CredentialsOutput *ackv1alpha1.SecretKeyReference `json:"credentialsOutput,omitempty"`
	// The expiration configuration for the external account binding.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	Expiration *Expiration `json:"expiration,omitempty"`
	// The ARN of the IAM role associated with the external account binding.
	// The role's trust policy must grant acm-acme.amazonaws.com access to
	// sts:AssumeRole, sts:SetSourceIdentity, and sts:TagSession.
	//
	// The Amazon Resource Name (ARN) of the IAM role to associate with the external
	// account binding.
	//
	// Regex Pattern: `^arn:aws[a-z-]*:iam::[0-9]{12}:role/.+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	RoleARN *string                                  `json:"roleARN,omitempty"`
	RoleRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"roleRef,omitempty"`
	// One or more tags to associate with the external account binding.
	Tags []*Tag `json:"tags,omitempty"`
}

// AcmeExternalAccountBindingStatus defines the observed state of AcmeExternalAccountBinding
type AcmeExternalAccountBindingStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The time at which the external account binding was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The time at which the external account binding expires.
	// +kubebuilder:validation:Optional
	ExpiresAt *metav1.Time `json:"expiresAt,omitempty"`
	// The external account binding key identifier. This value is not sensitive and
	// pairs with the macKey stored in the credentials Secret. It is surfaced in status
	// so ACME clients can reference it directly when registering an account.
	// +kubebuilder:validation:Optional
	KeyID *string `json:"keyID,omitempty"`
	// The time at which the external account binding was last used.
	// +kubebuilder:validation:Optional
	LastUsedAt *metav1.Time `json:"lastUsedAt,omitempty"`
	// The time at which the external account binding was revoked.
	// +kubebuilder:validation:Optional
	RevokedAt *metav1.Time `json:"revokedAt,omitempty"`
	// The time at which the external account binding was last updated.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// AcmeExternalAccountBinding is the Schema for the AcmeExternalAccountBindings API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type AcmeExternalAccountBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AcmeExternalAccountBindingSpec   `json:"spec,omitempty"`
	Status            AcmeExternalAccountBindingStatus `json:"status,omitempty"`
}

// AcmeExternalAccountBindingList contains a list of AcmeExternalAccountBinding
// +kubebuilder:object:root=true
type AcmeExternalAccountBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AcmeExternalAccountBinding `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AcmeExternalAccountBinding{}, &AcmeExternalAccountBindingList{})
}
